### ISSUE TITLE
ffmpeg-win64-v4.2.2.exe printing a line of text when playing

### ISSUE THREAD

**Issue by IC0okieI** [imageio/imageio-binaries#14]
Hello,
I have a question about the ffmpeg.exe file. I wrote a discord bot using discord.py, which plays audio when somebody joins a channel. I want that program to run in the background, so i use a .bat and a .vbs file so no command prompt appears when starting the script. Everytime the bot creates an audio source from mp3 files, it prints out a line "[mp3 @ 0000020168869040] Estimating duration from bitrate, this may be inaccurate". Therefore a console windows opens for 1sec to display this message and closes afterwards, which is really annoying. I use the ffmpeg-win64-v4.2.2.exe file with the discord.py lib to return an audio source, which can be played later "audio_source = discord.FFmpegPCMAudio(executable="E:/PythonPrograms/DiscordBotHallo/Dateien/ffmpeg-win64-v4.2.2.exe", source=source)". I actually dont know if this line of text comes from the ffmpeg .exe file or from the discord.py lib itself, but i got no answer on the discord server of the discord.py lib so i thought i ask my question where i downloaded the .exe file.
So if this message come from the .exe file. Is there a way to prevent this, so i can run my program in the background without any console window appearing?
Thanks
Cookie

my code if needed:
[main.txt](https://github.com/imageio/imageio-binaries/files/5883802/main.txt)

**Comment by almarklein** [comment]
In this library we use the same executable, and we don't have the popup, but this depends on *how* the exe is called. So I suspect that the `FFmpegPCMAudio` function calls the exe in a way that causes the window to pop up. It also should not matter whether or not any text is printed by the exe.

**Comment by IC0okieI** [comment]
Alright, thanks for your reply.
