### ISSUE TITLE
ValueError: Could not find a backend to open `50rgb.exr`` with iomode `wi`.

### ISSUE THREAD

**Issue by Bra1nsen** [imageio/imageio-binaries#20]
Guys I would like to save an 16 rgb bit array as .exr with imageio

```
		rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
		rgb_array[:, :, 0] = array16[1::2, 1::2] # red
		# Must avoid overflowing 16-bits in the addition here:
		rgb_array[:, :, 1] = (array16[0::2, 1::2].astype(int) + array16[1::2, 0::2]) / 2 # green
		rgb_array[:, :, 2] = array16[0::2, 0::2] # blue

		imageio.imwrite(f'{exp}rgb.exr', rgb_array)
```

**Comment by FirefoxMetzger** [comment]
@Bra1nsen You've found the repo that we use to store various binaries that can be downloaded as imageIO plugins. Could you create an issue in our main repo? (https://github.com/imageio/imageio/issues)

**Comment by Bra1nsen** [comment]
![12312312312](https://user-images.githubusercontent.com/58213050/192867190-c5fafa89-afdc-4ad8-b09c-cb4c19517553.png)
